version: '3'
services:
  web:
    image: joeplastic/silverstripe-base:7.3
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ~/.ssh:/tmp/.ssh:ro
    ports:
      - '80:80'
    environment:
      - VIRTUAL_HOST=local.dev
      #- NODE_VERSION=6.14.4
    networks:
      - example
    depends_on:
      - database

  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - example
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      UPLOAD_LIMIT: 3000000000
    networks:
      - example
    depends_on:
      - database  
      
  mailhog:
    image: mailhog/mailhog:latest
    restart: always    
    networks:
      - example
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui

volumes:
  db-data:

networks:
  example:
