---
Name: my-project-name-here
---
SilverStripe\Core\Manifest\ModuleManifest:
  project: app
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension
SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - 'app/production/editor.css'